name: FetchWorkflow 

on: [push]

jobs:
  Fetch:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Run fetch finding script 
      run: bash ./my-script.sh
    
